development:
  adapter: mysql2
  encoding: utf8
  database: test
  username: root
  password: z
  socket: /var/run/mysqld/mysqld.sock
#  strict: false
test:
  adapter: mysql2
  encoding: utf8
  database: idea_test
  username: root
  password: z
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: idea_test
  username: root
  password: z
  socket: /var/run/mysqld/mysqld.sock
