# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abdc4e38ac3c8820d1429e5a98a8d606b0ca151deef9e5de3a10a8eb0dc84d9ccbcdbe53d147fdcd7cb10c3739aef61e0bedcd11da71f9270b17a80b0a12d787

test:
  secret_key_base: 8ccff02153c860f33591aa7f712130de1d15fc844857349116a819d96ff8c8af9dcf2037d479db99edbae5acaabb18325a3d1c8296503b25eb1a63397b7d91db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
